/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoopRouteImport } from './routes/coop'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'

const CoopRoute = CoopRouteImport.update({
  id: '/coop',
  path: '/coop',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/coop': typeof CoopRoute
  '/bookings/new': typeof BookingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/coop': typeof CoopRoute
  '/bookings/new': typeof BookingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/coop': typeof CoopRoute
  '/bookings/new': typeof BookingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/bookings' | '/coop' | '/bookings/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/bookings' | '/coop' | '/bookings/new'
  id: '__root__' | '/' | '/admin' | '/bookings' | '/coop' | '/bookings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  CoopRoute: typeof CoopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coop': {
      id: '/coop'
      path: '/coop'
      fullPath: '/coop'
      preLoaderRoute: typeof CoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof BookingsRoute
    }
  }
}

interface BookingsRouteChildren {
  BookingsNewRoute: typeof BookingsNewRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsNewRoute: BookingsNewRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRouteWithChildren,
  CoopRoute: CoopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
